# Generated by Django 5.2.4 on 2025-08-11 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default='899625243', max_length=25, validators=[django.core.validators.RegexValidator(message="Contact number format: '+353899625243'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
