# Generated by Django 5.2.4 on 2025-08-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='coordinator',
            new_name='author',
        ),
    ]
