# Generated by Django 5.2.4 on 2025-08-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_rename_coordinator_trail_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='author',
            new_name='coordinator',
        ),
    ]
