# Generated by Django 5.2.4 on 2025-08-11 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_rename_author_trail_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trail',
            name='difficulty_level',
            field=models.CharField(default='cecva', max_length=20),
        ),
        migrations.AddField(
            model_name='trail',
            name='distance',
            field=models.CharField(default='cecva', max_length=15),
        ),
        migrations.AddField(
            model_name='trail',
            name='duration',
            field=models.CharField(default='cecva', max_length=20),
        ),
        migrations.AddField(
            model_name='trail',
            name='meeting_point',
            field=models.CharField(default='ceva', max_length=55),
        ),
        migrations.AddField(
            model_name='trail',
            name='type',
            field=models.CharField(default='cecva', max_length=20),
        ),
    ]
