# Generated by Django 5.2.4 on 2025-08-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_trail_date_posted_trail_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='date',
            field=models.DateTimeField(default='1998-10-12'),
        ),
    ]
