# Generated by Django 5.2.4 on 2025-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_trail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trail',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trail',
            name='meeting_point',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='trail',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
