# Generated by Django 5.2.4 on 2025-08-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_alter_trail_date_alter_trail_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='coordinator',
            new_name='coordinator_id',
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'EASY'), ('moderate', 'MODERATE'), ('challenging', 'CHALLEGNING'), ('hard', 'HARD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trail',
            name='type',
            field=models.CharField(choices=[('hiking', 'HIKING'), ('bike', 'Bike'), ('running', 'RUNNING')], max_length=20),
        ),
    ]
