# Generated by Django 5.2.4 on 2025-08-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_rename_coordinator_trail_coordinator_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='coordinator_id',
            new_name='coordinator',
        ),
        migrations.AlterField(
            model_name='trail',
            name='meeting_point',
            field=models.CharField(max_length=50),
        ),
    ]
