# Generated by Django 5.2.4 on 2025-08-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_rename_coordinator_id_trail_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='title',
            field=models.CharField(default='New trail', max_length=20),
        ),
    ]
